#164361854 User should be able to reset password
ann-mukundi/questioner pull request #11
Opened 2019-03-09 20:14 UTC by Philipotieno

#### What does this PR do?
- Test for password rest using email
#### Description of Task to be completed?
- Add configurations and update settings to enable password to be reset by mail
#### How should this be manually tested?
- `$ git clone https://github.com/Ogutu-Brian/questioners.git`
- `$ git fetch origin` - To get all branches
- `$ git checkout ft-password-reset-164361854`
- Create a virtual environment and activate it
        `$ virtualenv -p python3 venv`
        ` $ source venv/bin/activate`
- Add a .env file as in the .env.example
        `$ source .env`
- ` $ pip intsall -r requirements.txt`
- ` $ python api/manage.py runserver
- Test the following endpoints on postman
   - `/api/auth/signup/`
   - `/api/auth/activate/` 
   - `/api/auth/reset_password/`
   - `/api/auth/reset_password_confirm?uid=string_uid&token=generated_token url)`
#### Any background context you want to provide?
- Use a [desposable email ](https://temp-mail.org)
#### What are the relevant pivotal tracker stories?
- [#164361854](https://www.pivotaltracker.com/n/projects/2315729/stories/164361854)
#### Screenshots
![reset](https://user-images.githubusercontent.com/29012135/54076803-8f7d0500-42c0-11e9-9663-e49e4cf84b72.png)

![Screenshot from 2019-03-08 01-35-58](https://user-images.githubusercontent.com/29012135/54076784-4b8a0000-42c0-11e9-9577-e88bef0d796c.png)

2019-03-10 18:54 UTC, Ogutu-Brian approved these changes
Good job on the reset password. I  like the way you handled the token generated for reset password.

2019-03-10 19:13 UTC, Ogutu-Brian requested changes
Hello @Philipotieno ,
For reset to be done, there are two endpoints that are involved. Use the `POST api/auth/reset_password/` to get reset password token and `POST api/auth/reset_password_confirm` to reset your password. Include the two in your test for reset password instead of using the signup token.

2019-03-11 10:07 UTC, Ogutu-Brian approved these changes

2019-03-11 11:23 UTC, IssaIan approved these changes

2019-03-12 05:48 UTC, Amoswachira approved these changes
good i see the tests are now passing

2019-03-12 11:48 UTC, matthenge approved these changes

2019-03-12 11:49 UTC, merged