#164869458 view specific question for a specific meetup
ann-mukundi/questioner pull request #35
Opened 2019-03-25 17:18 UTC by a-braham

#### What does this PR do?
- Has view endpoint for viewing a specific question
#### Description of Task to be completed?
- `GET  api/meetups/{meetup_id}/questions/{question_id}/question`
#### How should this be manually tested?
After cloning the repo
- cd into questioner, checkout to branch `bg-view-specific-question-164869458`
- run tests `python api/manage.py test`
#### Screenshots

2019-03-25 17:22 UTC, Amoswachira commented
@a-braham don't forget to  resolve the merge conflicts

2019-03-25 17:23 UTC, Amoswachira reviewed
@a-braham don't forget to resolve the merge conflicts

2019-03-26 00:58 UTC, Ogutu-Brian commented
Hello @a-braham ,
Would you add screenshot and relevant pivotal tracker stories to the PR

2019-03-26 07:17 UTC, IssaIan submitted a review, later dismissed
But remember to add necessary screenshots as suggested. You could also reduce the number of return statements within a function next time. Otherwise great work.

2019-03-26 07:41 UTC, Bakley requested changes
Kindly update your documentation before merging
![ab](https://user-images.githubusercontent.com/7009215/54979236-b53e2580-4fb3-11e9-8a6c-1c5798c83b9b.png)

2019-03-26 08:07 UTC, Bakley submitted a review, later dismissed

2019-03-26 08:16 UTC, Bakley commented
Hey, @a-braham I tested your PR and it meets my expectation. The test were passing and it was fetching the right meetup. The error message response was also good enough. Great work on this. Kindly add now the screenshots to the PR for easy visibility.

2019-03-26 08:56 UTC, davenjeru requested changes

2019-03-26 08:56 UTC, davenjeru commented on api/questions/urls.py
> +    path('<str:m_id>/questions/<str:id>/question',
This `/question` at the end is unnecessary @a-braham. The URL should be `GET /api/meetups/{meetupId}/questions/{questionId}`

2019-03-26 08:56 UTC, davenjeru commented on api/config/swagger.py
> +                    url='/api/meetups/{meetupId}/questions/{questionId}/question',
This `/question` at the end is unnecessary @a-braham. The URL should be `GET /api/meetups/{meetupId}/questions/{questionId}`

2019-03-26 09:05 UTC, IssaIan requested changes

2019-03-26 09:05 UTC, IssaIan commented on api/config/swagger.py
> +                    url='/api/meetups/{meetupId}/questions/{questionId}/question',
Also change this url in the swagger documentation to what @davenjeru adviced.

2019-03-26 09:55 UTC, IssaIan approved these changes

2019-03-26 10:29 UTC, Ogutu-Brian approved these changes

2019-03-26 10:32 UTC, Philipotieno requested changes

2019-03-26 10:32 UTC, Philipotieno commented on api/config/swagger.py
> +    return response.Response(schema)
@a-braham Could use autopep8  to make sure a new line is added at the end of the file and everything is to standard

2019-03-26 10:56 UTC, Philipotieno approved these changes

2019-03-26 11:14 UTC, davenjeru approved these changes

2019-03-26 11:15 UTC, merged